version: "3"
services:
  pyspark-notebook:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
      - "4040:4040" 
    volumes:
      - ./notebooks:/home/jovyan/work  
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
